name: node

on: push

jobs:
  install:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ${{ github.workspace }}/test/db:/docker-entrypoint-initdb.d
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marketplace
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Chown user
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: linter
        run: npm run lint
        if: ${{ always() }}
      - name: test
        run: npm run test
      - name: integration test
        run: npm run test:integration
      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
