name: node

on: push

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ${{ github.workspace }}/init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marketplace
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint /bin/bash "docker-entrypoint.sh"

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: linter
        run: npm run lint
        if: ${{ always() }}
      - name: test
        run: npm run test
      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
